services:

  keycloak:
    build:
      context: ../keycloak
      dockerfile: Dockerfile
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://localhost:5432/chimera_db
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: password
      KC_HOSTNAME: localhost
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: keyclock
    ports:
      - "3000:8080" # Map port 3000 on the host to port 8080 in the container
    depends_on:
      - postgres
    command: ["start-dev"]
    networks:
      - key_clock
volumes:
  postgres_data:

networks:
  key_clock:
