image: maven:3.8.3-openjdk-17

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  DOCKER_IMAGE: "$CI_REGISTRY_IMAGE/chimera:latest" 

stages:
  - build
  - docker

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - |
      echo "Maven Path : $(whereis mvn)"
      echo "Java Path : $(whereis java)"
      mvn clean package -DskipTests
      mkdir -p build/application-files
      find $CI_PROJECT_DIR -type f -name "*.jar" -exec mv {} build/application-files/ \;
      ls -lart build/application-files/
  artifacts:
    paths:
      - build/application-files/*.jar
    expire_in: 1 week

build_and_push_docker:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - |
      echo "Files recieved from Previous Step"
    - ls -lart build/application-files/
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
