version: '3.8'

# Mohit - we need to take care of security, pprof, health checks, zpages, etc.

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:${OTEL_VERSION:-0.38.0}
    container_name: otel-collector
    ports:
      - "${OTEL_GRPC_PORT:-4317}:4317"
      - "${OTEL_HTTP_PORT:-4318}:4318"
      - "${ZIPKIN_PORT:-55681}:55681" # Mohit, does it take care of zPages. zPages are an in-process diagnostic tool used in OpenTelemetry to provide live, in-memory diagnostics for tracing and metrics data
      - "${PROMETHEUS_PORT:-8888}:8888" # Prometheus metrics exposed by the Collector
      - "${PROMETHEUS_EXPORTER_METRICS_PORT:-8889}:8889" # Prometheus exporter metrics
      - "${OTEL_COL_HEALTH_CHECK_EXTENSION:-13133}:13133"
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    command:
      - "--config=/etc/otelcol-contrib/config.yaml"
    networks:
        - chimera