CREATE TABLE USER_FUNCTION_ACCESS_MAST
(
ACC_ID        bigserial PRIMARY KEY,
FUNCTION_ID   bigint,
ORG_ID        VARCHAR(50 ),
USER_ROLE_ID  VARCHAR(50 ),
EMP_ID       VARCHAR(100),
ACCESS_LEVEL  VARCHAR(2),
PMD_ROLE      bigint,
ATTRIBUTE_1   VARCHAR(50),
ATTRIBUTE_2   VARCHAR(50),
ATTRIBUTE_3   VARCHAR(50),
ATTRIBUTE_4   VARCHAR(50),
ATTRIBUTE_5   VARCHAR(50),
STATUS         VARCHAR(1)             DEFAULT 'A',
INSERTED_USER  VARCHAR(500)             DEFAULT current_user ,
INSERT_DT      DATE                           DEFAULT current_timestamp ,
MODIFIED_BY    VARCHAR(500),
UPDATE_DT      DATE
)