keycloak:
  admin:
    server-url: http://localhost:3000
    username: admin
    password: keyclock
  setup:
    realm: chimera
    client:
      clientId: chimera_api_client
      enabled: true
      publicClient: true
      redirectUris:
        - "http://localhost:8080/*"
    roles:
      - name: chimera_user
        description: Regular user
      - name: chimera_admin
        description: Administrator
    groups:
      - name: users
        roles: [chimera_user]
      - name: admins
        roles: [chimera_admin]
    users:
      - username: user_test
        password: password1
        roles: [USER]
        groups: [users]
      - username: admin_test
        password: admin123
        roles: [ADMIN]
        groups: [admins]