version: '3.8'
services:
  jaeger:
    image: jaegertracing/all-in-one:${JAEGER_VERSION:-latest}
    container_name: jaeger
    ports:
      - "${JAEGER_UI_PORT:-16686}:16686"
      - "${JAEGER_HTTP_PORT:-14268}:14268"
      - "${JAEGER_GRPC_PORT:-14250}:14250"
      - "${ZIPKIN_API_PORT:-9411}:9411"
    networks:
        - observability