version: '3.8'

services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault-dev
    restart: always
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_ADDR: localhost:8200
      VAULT_API_ADDR: localhost:8200
      VAULT_LOG_LEVEL: debug
    cap_add:
      - IPC_LOCK
    command: vault server -dev
    volumes:
      - vault_data:/vault/data

volumes:
  vault_data:
