version: '3.8'

services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    command: server -config=/vault/config/config.hcl
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault/config:/vault/config
      - ./vault/data:/vault/data
    networks:
      - vault-net

networks:
  vault-net:
