version: '3.8'

services:
  vault:
    image: hashicorp/vault:${VAULT_VERSION:-1.18.4}
    container_name: vault
    restart: on-failure:3
    command: "vault server -config=/vault/config/vault-config.hcl"
    ports:
      - "8200:8200"
    volumes:
      - vault-data:/vault/data
      - ./vault-config.hcl:/vault/config/vault-config.hcl
      # - /path/to/vault/logs:/var/log
    environment:
      # VAULT_DEV_ROOT_TOKEN_ID: "root"
      # VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
      VAULT_ADDR: "http://0.0.0.0:8200"
    cap_add:
      - IPC_LOCK # Required to lock memory for security
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8200/v1/sys/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
        - chimera
    depends_on:
      postgres:
        condition: service_healthy

volumes:
    vault-data: