services:
  temporal:
    image: temporalio/auto-setup:${TEMPORAL_VERSION}
    container_name: temporal
    environment:
      - TEMPORAL_CLI_ADDRESS=temporal:7233
      - DB=postgres12_pgx
      - DB_PORT=5432
      - POSTGRES_USER=chimera
      - POSTGRES_PWD=chimera123
      - POSTGRES_SEEDS=postgres
      - POSTGRES_DB=chimera_db
      - DYNAMIC_CONFIG_FILE_PATH=/etc/temporal/config/dynamicconfig/development-sql.yaml
      - ENABLE_ES=true
      - ES_SEEDS=opensearch
      - ES_VERSION=v7
      - LOG_LEVEL=info
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig
#    healthcheck: the health return HTTP/0.9 response, and hence commented out for now
#      test: [ "CMD", "curl", "-f", "http://localhost:7233/health" ]
#      interval: 30s
#      timeout: 30s
#      retries: 3
    ports:
      - 7233:7233
    depends_on:
      postgres:
        condition: service_healthy
      opensearch:
        condition: service_healthy
    networks:
      - chimera

  temporal-admin-tools:
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:${TEMPORAL_ADMINTOOLS_VERSION}
    networks:
      - chimera
    stdin_open: true
    tty: true
  temporal-ui:
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    image: temporalio/ui:${TEMPORAL_UI_VERSION}
    networks:
      - chimera
    ports:
      - 8080:8080
