version: '3.8'

services:
    trino:
        build:
          context: .
          dockerfile: Dockerfile
        container_name: trino
        depends_on:
          postgres:
            condition: service_healthy
        environment:
          - TRINO_ENVIRONMENT=production
          - HTTP_SERVER_HTTP_PORT=10100
          # - WEB_UI_ENABLED=true
        networks:
          - chimera
        ports:
            - "10100:10100"