services:
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - key_clock

  keycloak:
    build:
      context: ../../Setup/keycloak
      dockerfile: Dockerfile
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak_db
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: password
      KC_HOSTNAME: localhost
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: keyclock
    ports:
      - "3000:8080" # Map port 3000 on the host to port 8080 in the container
    depends_on:
      - postgres
    command: ["start-dev"]
    networks:
      - key_clock
volumes:
  postgres_data:

networks:
  key_clock:
