services:
  otel-collector:
    extends:
      file: otel-collector/otel-collector.yml
      service: otel-collector
    environment:
      - OTEL_VERSION=0.38.0
      - OTEL_GRPC_PORT=4317
      - OTEL_HTTP_PORT=4318
      - ZIPKIN_PORT=5q5681
      - PROMETHEUS_PORT=8888

  jaeger:
    extends:
      file: jaeger/jaeger.yml
      service: jaeger
    environment:
      - JAEGER_VERSION=1.29.0
      - JAEGER_UI_PORT=16686
      - JAEGER_HTTP_PORT=14268
      - JAEGER_GRPC_PORT=14250
      - ZIPKIN_API_PORT=9411

  prometheus:
    extends:
      file: prometheus/prometheus-server.yml
      service: prometheus
    environment:
      - PROMETHEUS_VERSION=${PROMETHEUS_VESION:-3.1.0}
      - PROMETHEUS_UI_PORT=9090
    networks:
      - observability

  grafana:
    extends:
      file: grafana/grafana.yml
      service: grafana
    environment:
      - GRAFANA_VERSION=${GRAFANA_VERSION:-7.5.5}
      - GRAFANA_PORT=3000
    networks:
      - observability

  postgres:
    extends:
      file: postgresql/postgres.yml
      service: postgres
#    environment:
#      - POSTGRES_USER=admin
#      - POSTGRES_PASSWORD=password
#      - POSTGRES_DB=chimera_db


  api-gateway:
    extends:
      file: api-gateway/api-gateway.yml
      service: kong-gateway
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=chimera_db
    networks:
      - kong-net
    depends_on:
      - kong-migrations

  kong-migrations:
    image: kong:latest
    command: kong migrations bootstrap
    networks:
      - kong-net

  keycloak:
    extends:
      file: keycloak/keycloak-docker-compose.yml
      service: keycloak
    environment:
      - KC_DB=${KC_DB:-postgres}
      - KC_DB_URL=${KC_DB_URL:-jdbc:postgresql://postgres:5432/chimera_db}
      - KC_DB_USERNAME=${KC_DB_USERNAME:-admin}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD:-password}
      - KC_HOSTNAME=${KC_HOSTNAME:-localhost}
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KC_BOOTSTRAP_ADMIN_USERNAME:-admin}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KC_BOOTSTRAP_ADMIN_PASSWORD:-keyclock}


#  taskmanager:
#    extends:
#      file: flink/env-compose.yml
#      service: taskmanager
#    environment:
#      - FLINK_VERSION=1.13.2
#    networks:
#      - engine
#    depends_on:
#      - jobmanager
#
#  jobmanager:
#    extends:
#      file: flink/env-compose.yml
#      service: jobmanager
#    environment:
#      - FLINK_VERSION=1.13.2
#    networks:
#      - engine
#
#  zookeeper:
#    extends:
#      file: flink/env-compose.yml
#      service: zookeeper
#    environment:
#      - FLINK_VERSION=1.13.2
#    networks:
#      - engine
#
#  kafka:
#    extends:
#        file: flink/env-compose.yml
#        service: kafka
#    environment:
#      - FLINK_VERSION=1.13.2
#    networks:
#        - engine

networks:
  observability:
    driver: bridge
  kong-net:
    driver: bridge
  engine:
    driver: bridge
  postgresql:
    driver: bridge
  key_clock:
    driver: bridge

volumes:
  postgres_data: