services:
  postgres:
    extends:
      file: postgresql/postgres.yml
      service: postgres

  api-gateway:
    extends:
      file: api-gateway/api-gateway.yml
      service: kong-gateway

  kong-migrations:
    extends:
      file: api-gateway/api-gateway.yml
      service: kong-migrations

  keycloak:
    extends:
      file: keycloak/keycloak-docker-compose.yml
      service: keycloak

  otel-collector:
    extends:
      file: otel-collector/otel-collector.yml
      service: otel-collector

  jaeger:
    extends:
      file: jaeger/jaeger.yml
      service: jaeger

  prometheus:
    extends:
      file: prometheus/prometheus-server.yml
      service: prometheus

  grafana:
    extends:
      file: grafana/grafana.yml
      service: grafana

# Below To be fixed
#  taskmanager:
#    extends:
#      file: flink/env-compose.yml
#      service: taskmanager
#    environment:
#      - FLINK_VERSION=1.13.2
#    networks:
#      - engine
#    depends_on:
#      - jobmanager
#
#  jobmanager:
#    extends:
#      file: flink/env-compose.yml
#      service: jobmanager
#    environment:
#      - FLINK_VERSION=1.13.2
#    networks:
#      - engine
#
#  zookeeper:
#    extends:
#      file: flink/env-compose.yml
#      service: zookeeper
#    environment:
#      - FLINK_VERSION=1.13.2
#    networks:
#      - engine
#
#  kafka:
#    extends:
#        file: flink/env-compose.yml
#        service: kafka
#    environment:
#      - FLINK_VERSION=1.13.2
#    networks:
#        - engine

networks:
  chimera:
    driver: bridge

volumes:
    postgres_data: