services:
  otel-collector:
    extends:
      file: otel-collector/otel-collector.yml
      service: otel-collector
    environment:
      - OTEL_VERSION=0.38.0
      - OTEL_GRPC_PORT=4317
      - OTEL_HTTP_PORT=4318
      - ZIPKIN_PORT=55681
      - PROMETHEUS_PORT=8888

  jaeger:
    extends:
      file: jaeger/jaeger.yml
      service: jaeger
    environment:
      - JAEGER_VERSION=1.29.0
      - JAEGER_UI_PORT=16686
      - JAEGER_HTTP_PORT=14268
      - JAEGER_GRPC_PORT=14250
      - ZIPKIN_API_PORT=9411

  prometheus:
    extends:
      file: prometheus/prometheus-server.yml
      service: prometheus
    environment:
      - PROMETHEUS_VERSION=2.26.0
      - PROMETHEUS_UI_PORT=9090
    networks:
      - observability

  grafana:
    extends:
      file: grafana/grafana.yml
      service: grafana
    environment:
      - GRAFANA_VERSION=7.5.5
      - GRAFANA_PORT=3000
    networks:
      - observability

#  postgres-db:
#    extends:
#      file: services/postgres-db.yml
#      service: postgres-db
#    environment:
#      - POSTGRES_VERSION=13-alpine3.17
#      - POSTGRES_PORT=5432

networks:
  observability:
    driver: bridge