# kubernetes.yaml
apiVersion: v1
kind: List
items:
  - $(cat common/configmap.yaml)
  - $(cat common/secret.yaml)
  - $(cat grafana/deployment.yaml)
  - $(cat grafana/service.yaml)
  - $(cat prometheus/deployment.yaml)
  - $(cat prometheus/service.yaml)
  - $(cat jaeger/deployment.yaml)
  - $(cat jaeger/service.yaml)
