apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: observability
  labels:
    app: jaeger
spec:
  type: ClusterIP
  ports:
    - name: collector-http
      protocol: TCP
      port: 14268
      targetPort: 14268
    - name: query-http
      protocol: TCP
      port: 16686
      targetPort: 16686
    - name: otlp-grpc
      protocol: TCP
      port: 14250
      targetPort: 14250
    - name: zipkin-api
      protocol: TCP
      port: 9411
      targetPort: 9411
  selector:
    app: jaeger
