apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          env:
            - name: PROMETHEUS_PORT
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: PROMETHEUS_PORT
          ports:
            - containerPort: 9090 # Prometheus web UI and API port
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/
              readOnly: true
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config # ConfigMap containing Prometheus configuration
