apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: observability
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s

    scrape_configs:
      - job_name: 'system-metrics'
        static_configs:
          - targets: ['host.docker.internal:8083']
      - job_name: 'otel-collector'
        static_configs:
          - targets: ['otel-collector:8888']
      - job_name: 'spark'
        metrics_path: '/metrics/prometheus'
        static_configs:
          - targets:
              - 'localhost:4040'
              - 'worker-node1:8080'
              - 'worker-node2:8080'
      - job_name: 'chimera_app_spark'
        metrics_path: '/metrics/prometheus'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: spark
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            target_label: __metrics_path__
          - source_labels: [__address__]
            target_label: __address__
            replacement: $1
      - job_name: 'flink'
        metrics_path: /metrics
        static_configs:
          - targets:
              - 'flink-jobmanager:9249'
              - 'flink-taskmanager:9249'
      - job_name: 'grafana'
        static_configs:
          - targets: ['grafana:3000']