metadata:
  JdbcUrl : "jdbc:postgresql://localhost:5432/postgres"
  Username : "postgres"
  Password : "root"
  DriverClassName : "org.postgresql.Driver"
  MaximumPoolSize : "10"
  MinimumIdle : "2"
  IdleTimeout : "600000"
  MaxLifetime : "1800000"
  ConnectionTimeout : "30000"
localrds:
  JdbcUrl : "jdbc:postgresql://localhost:5432/postgres"
  Username : "postgres"
  Password : "root"
  DriverClassName : "org.postgresql.Driver"
  MaximumPoolSize : "10"
  MinimumIdle : "2"
  IdleTimeout : "600000"
  MaxLifetime : "1800000"
  ConnectionTimeout : "30000"