application:
  name: RDSConfig
  version: 1.0.0
  environment:
    test:
      url: "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
      username : "sa"
      password : ""
      DriverClassName : "org.h2.Driver"
    dev:
      url: "jdbc:postgresql://localhost:5432/chimera_db"
      username : "chimera"
      password : "chimera123"
      DriverClassName : "org.postgresql.Driver"
      MaximumPoolSize : "10"
      MinimumIdle : "2"
      IdleTimeout : "600000"
      MaxLifetime : "1800000"
      ConnectionTimeout : "30000"
      Default : "N"
      CloudProvider : "local"
      RDSSecretName : "AWS SECRET NAME"
      GCPProjectId : ""
      AZUREKeyVaultURL : ""
    sit:
      url: "jdbc:p6spy:postgresql://localhost:5432/chimera_db"
      username: "chimera"
      password: "chimera123"
      DriverClassName: "com.p6spy.engine.spy.P6SpyDriver"
      MaximumPoolSize: "10"
      MinimumIdle: "2"
      IdleTimeout: "600000"
      MaxLifetime: "1800000"
      ConnectionTimeout: "30000"
      Default: "N"
      CloudProvider: "GCP"
      RDSSecretName: "GCP SECRET NAME"
      GCPProjectId: "your-gcp-project-id"
      AZUREKeyVaultURL: ""
    prod:
      url: "jdbc:postgresql://localhost:5432/chimera_db"
      username: "chimera"
      password: "chimera123"
      DriverClassName: "org.postgresql.Driver"
      MaximumPoolSize: "10"
      MinimumIdle: "2"
      IdleTimeout: "600000"
      MaxLifetime: "1800000"
      ConnectionTimeout: "30000"
      Default: "N"
      CloudProvider: "AZURE"
      RDSSecretName: "AZURE SECRET NAME"
      GCPProjectId: ""
      AZUREKeyVaultURL: "https://<your-key-vault-name>.vault.azure.net/"