CREATE TABLE OrganizationTypes
(
ORG_TYPE_ID       bigserial PRIMARY KEY,
ORY_TYPE_NAME         VARCHAR(50),
ORG_TYPE_DESC       VARCHAR(4000),
USER_FIELD_1   VARCHAR(500),
USER_FIELD_2   VARCHAR(500),
USER_FIELD_3   VARCHAR(500),
USER_FIELD_4   VARCHAR(500),
USER_FIELD_5   VARCHAR(500),
STATUS         VARCHAR(1)             DEFAULT 'A',
INSERTED_USER  VARCHAR(500)           DEFAULT current_user ,
INSERT_DT      DATE                   DEFAULT current_timestamp ,
MODIFIED_BY    VARCHAR(500),
UPDATE_DT      DATE
)