CREATE TABLE APP_FUNCTIONS_MAST
(
FUNCTION_ID          bigserial PRIMARY KEY,
FUNCTION_ITEM       VARCHAR(50),
FUNCTION_TYPE       VARCHAR(4000)       DEFAULT 'MM',
PARENT_FUNCTION_ID  bigint,
HYPERLINK           VARCHAR(1000),
ATTRIBUTE_1         VARCHAR(50),
ATTRIBUTE_2         VARCHAR(50),
ATTRIBUTE_3         VARCHAR(50),
ATTRIBUTE_4         VARCHAR(50),
ATTRIBUTE_5         VARCHAR(50),
STATUS         VARCHAR(1)             DEFAULT 'A',
INSERTED_USER  VARCHAR(500)             DEFAULT current_user ,
INSERT_DT      DATE                           DEFAULT current_timestamp ,
MODIFIED_BY    VARCHAR(500),
UPDATE_DT      DATE
);