version: '3.8'
services:
  postgres:
    image: postgres:16.7
    container_name: postgres
    # restart: always
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      - POSTGRES_USER=init_user
      - POSTGRES_PASSWORD=init_password
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "init_user" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
      # - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
    # entrypoint: /usr/local/bin/entrypoint.sh
    networks:
      - chimera
  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres_exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/postgres?sslmode=disable
    ports:
      - ${POSTGRES_EXPORTER_PORT:-9187}:9187
    depends_on:
      - postgres
    networks:
      - chimera
networks:
    chimera:
        driver: bridge
volumes:
    postgres_data:
