version: '3.8'
services:
  postgres:
    image: postgres:16.7
    container_name: postgres
    # restart: always
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      - POSTGRES_USER=init_user
      - POSTGRES_PASSWORD=init_password
      # - POSTGRES_DB=chimera_db
      # - POSTGRES_USER=admin
      # - POSTGRES_PASSWORD=password
      # - POSTGRES_DB=chimera_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
      # - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
    # entrypoint: /usr/local/bin/entrypoint.sh
    networks:
      - postgresql