name: Chimera Docker Build & Publish

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build all modules with Maven
        run: mvn clean package -DskipTests

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images for each JAR
        run: |
          for jar in $(find . -name "*.jar" -not -path "*/target/original-*.jar"); do
            module_dir=$(dirname "$jar")
            module_name=$(basename $(dirname "$jar"))
            image_name="ghcr.io/${{ github.repository_owner }}/${module_name}:latest"
            echo "Processing $jar in module $module_name"

            # Use a Dockerfile in each module, or copy a template if not present
            if [ ! -f "$module_dir/Dockerfile" ]; then
              echo "No Dockerfile found in $module_dir, creating a simple Dockerfile"
              cat > $module_dir/Dockerfile <<EOF
FROM eclipse-temurin:17-jre
COPY $(basename $jar) /app.jar
ENTRYPOINT ["java", "-jar", "/app.jar"]
EOF
            fi

            cp "$jar" "$module_dir/$(basename $jar)"
            docker build -t $image_name $module_dir
            docker push $image_name
          done
